name: 'GitHub Action for Push'
description: 'Build docker image'
inputs:
  dockerfile:
    description: 'specify Dockerfile to use'
    required: false
    default: 'Dockerfile'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -f ${{ inputs.dockerfile }}
branding:
  icon: 'upload-cloud'
  color: 'green'